server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acm
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  resources:
    static-locations: classpath:/testStatic/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/pic/,file:D:/pic/photo/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 6MB
      enabled: true
      resolve-lazily: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

passUrl: http://localhost:8888
excludedUri: /*